{% set name = "yarl" %}
{% set version = "1.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ec8cfe2295f3e5e44c51f57272afbd69414ae629ec7c6b27f5a410efc78b70a0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - cython                                 # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - expandvars
    - tomli  # [py<311]
    - cython
    - setuptools
  run:
    - python
    - multidict >=4.0
    - idna >=2.0
    - typing-extensions >=3.7.4  # [py<38]

test:
  source_files:
    - tests
  requires:
    - pytest
    - pip
  commands:
    - py.test tests
    - pip check

about:
  home: https://github.com/aio-libs/yarl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Yet another URL library
  doc_url: http://yarl.readthedocs.io
  dev_url: https://github.com/aio-libs/yarl
  doc_source_url: https://github.com/aio-libs/yarl/tree/master/docs

extra:
  recipe-maintainers:
    - sodre
    - xhochy
