{% set name = "yarl" %}
{% set version = "1.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 20d95535e7d833889982bfe7cc321b7f63bf8879788fee982c76ae2b24cfb715

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - cython                                 # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - expandvars
    - tomli  # [py<311]
    - cython
    - setuptools
  run:
    - python
    - multidict >=4.0
    - idna >=2.0
    - propcache >=0.2.0

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-codspeed
    - hypothesis >=6.0
    - pip
  commands:
    - py.test tests
    - pip check

about:
  home: https://github.com/aio-libs/yarl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Yet another URL library
  doc_url: http://yarl.readthedocs.io
  dev_url: https://github.com/aio-libs/yarl
  doc_source_url: https://github.com/aio-libs/yarl/tree/master/docs

extra:
  recipe-maintainers:
    - sodre
    - xhochy
